### ISSUE TITLE
Failed to execute the Introduction code.

### ISSUE THREAD

**Issue by rysh** [flix/programming-flix#50]
Second paragraph of the introduction page
I tried to run the code that introduces polymorphic records in the playground, but failed.
<img width="1397" alt="スクリーンショット 2021-12-15 10 18 17" src="https://user-images.githubusercontent.com/828709/146105087-a85489fa-a3c0-4544-aada-d5140d31cec0.png">
It would be sad if an error occurred in the Introduction code, so I want to worked properly.

And if someone can give me some pointers on how to fix it, I'd like to try it.

**Comment by mlutze** [comment]
Thanks for pointing this out.

We had a syntax change a while ago:

- `Record` has become `RecordRow`.
- The `:` in record types has become `::`.

You can make those changes in the `Introduction.js` file.

**Comment by magnus-madsen** [comment]
Fixed thanks to @rysh
