### ISSUE TITLE
Rewrite `Effects`'s paragraph with impure function argument

### ISSUE THREAD

**Issue by ninaandrup** [flix/programming-flix#62]
The page `Effects` has [this paragraph](https://github.com/flix/programming-flix/blob/6864d39b90922b78f8d3e5be7ae26b915e367166/src/content/Effects.js#L62) which explains "A higher-order function can also require that a function is impure.". But the syntax `~>` used in this example
```
def foreach(f: a ~> Unit, l: List[a]): Unit & Impure
```
is not allowed anymore. And the paragraph should be rewritten.

**Comment by ninaandrup** [comment]
[This table](https://github.com/flix/programming-flix/blob/6864d39b90922b78f8d3e5be7ae26b915e367166/src/content/Effects.js#L229) also specifies that the shorthand notation `a ~> b` can be used instead of `a -> b & Impure`.

**Comment by magnus-madsen** [comment]
This can no longer be required and so the text should be removed :)
