### ISSUE TITLE
Rewrite `Interoperability` to include return types of imports

### ISSUE THREAD

**Issue by ninaandrup** [flix/programming-flix#63]
[This sentence](https://github.com/flix/programming-flix/blob/6864d39b90922b78f8d3e5be7ae26b915e367166/src/content/Interoperability.js#L84) is out-of-date, since we know always specify return types of java imports.

The `Interoperability` page should be updated to let the user know to specify the return type and effect of imports.

In [the summary](https://github.com/flix/programming-flix/blob/6864d39b90922b78f8d3e5be7ae26b915e367166/src/content/Interoperability.js#L180) the return types are not included either.

**Comment by ninaandrup** [comment]
@magnus-madsen Do you want to rewrite this, or should I do it?

**Comment by magnus-madsen** [comment]
Yes, give it a go :)
