### ISSUE TITLE
Rewrite `Interoperability`'s `Invoking Static Methods` paragraph

### ISSUE THREAD

**Issue by ninaandrup** [flix/programming-flix#64]
We have changed the syntax of importing static methods from
```
import java.lang.String:valueOf(Bool);
valueOf(true)
```
to
```
import static java.lang.String.valueOf(Bool);
valueOf(true)
```

The paragraph can be found [here](https://github.com/flix/programming-flix/blob/6864d39b90922b78f8d3e5be7ae26b915e367166/src/content/Interoperability.js#L180).

**Comment by ninaandrup** [comment]
@magnus-madsen Do you want to rewrite this, or should I do it?

**Comment by magnus-madsen** [comment]
I think you should give it an attempt :) You can do it 👍
