### ISSUE TITLE
Non-existing `Unsafe.println(x)`

### ISSUE THREAD

**Issue by ninaandrup** [flix/programming-flix#65]
The example in [this paragraph](https://github.com/flix/programming-flix/blob/6864d39b90922b78f8d3e5be7ae26b915e367166/src/content/TipsAndTricks.js#L105)
```
def sum(x: Int32, y: Int32): Int32 = 
    let _ = Unsafe.println(x);
    let _ = Unsafe.println(y);
    x + y
```
does not work. It looks like there is an `unsafePrint` in `Solver.flix`.

**Comment by magnus-madsen** [comment]
We have simply remove it. What you can do instead is:

```
let _ = println("Hello") as & Pure
```
