### ISSUE TITLE
`Using Flix to Solve Constraints on Lattices` example in `Fixpoints`

### ISSUE THREAD

**Issue by ninaandrup** [flix/programming-flix#67]
I cannot get [the example](https://github.com/flix/programming-flix/blob/6864d39b90922b78f8d3e5be7ae26b915e367166/src/content/Fixpoints.js#L371) to work, when I copy it into VS code.

**Comment by magnus-madsen** [comment]
@JonathanStarup Can you take a look? 

@ninaandrup Do you get any errors or what do you mean by it does not work?

**Comment by ninaandrup** [comment]
I get a couple of errors.
```
Missing implementation of 'lessEqual' required by class 'PartialOrder'.

46 | instance PartialOrder[Sign] {

              ^^^^^^^^^^^^
              missing implementation
```
And from main
```
>> Parse Error: Invalid input ';', expected "ref", "reify", "reifyBool", "reifyType", "reifyEff", LegalLetter, ':', "->", ArgumentList, '[', '.', "::", ":::", Op, '`', "<+>" or ** (line 105, column 22):
    query p select (r; v) from LocalVar(r; v) |> println;
```
Because of the `;` in `(r; v)`.

**Comment by paulbutcher** [comment]
What's involved in rolling out a new version of the website? I just ran into this and spent a while debugging, started putting together a PR to fix the website, and then found that it had already been fixed. Would be nice to save someone else the same busywork.

**Comment by paulbutcher** [comment]
While I'm here: any reason why we implement `Eq` etc by hand instead of simply using `with`?:

```
enum Sign with Boxable, Eq, Order, ToString {
```

**Comment by magnus-madsen** [comment]
> While I'm here: any reason why we implement `Eq` etc by hand instead of simply using `with`?:
> 
> ```
> enum Sign with Boxable, Eq, Order, ToString {
> ```

Don't know. 

But, Ill look into uploading the new version.

**Comment by magnus-madsen** [comment]
Updated!
